export interface CountryCode {
  code: string;
  name: string;
  dial: string;
  flag: string;
  maxDigits: number;
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: "AF", name: "Afghanistan", dial: "+93", flag: "🇦🇫", maxDigits: 9 },
  { code: "AL", name: "Albania", dial: "+355", flag: "🇦🇱", maxDigits: 9 },
  { code: "DZ", name: "Algeria", dial: "+213", flag: "🇩🇿", maxDigits: 9 },
  { code: "AS", name: "American Samoa", dial: "+1684", flag: "🇦🇸", maxDigits: 7 },
  { code: "AD", name: "Andorra", dial: "+376", flag: "🇦🇩", maxDigits: 9 },
  { code: "AO", name: "Angola", dial: "+244", flag: "🇦🇴", maxDigits: 9 },
  { code: "AI", name: "Anguilla", dial: "+1264", flag: "🇦🇮", maxDigits: 7 },
  { code: "AG", name: "Antigua & Barbuda", dial: "+1268", flag: "🇦🇬", maxDigits: 7 },
  { code: "AR", name: "Argentina", dial: "+54", flag: "🇦🇷", maxDigits: 10 },
  { code: "AM", name: "Armenia", dial: "+374", flag: "🇦🇲", maxDigits: 8 },
  { code: "AW", name: "Aruba", dial: "+297", flag: "🇦🇼", maxDigits: 7 },
  { code: "AU", name: "Australia", dial: "+61", flag: "🇦🇺", maxDigits: 9 },
  { code: "AT", name: "Austria", dial: "+43", flag: "🇦🇹", maxDigits: 13 },
  { code: "AZ", name: "Azerbaijan", dial: "+994", flag: "🇦🇿", maxDigits: 9 },
  { code: "BS", name: "Bahamas", dial: "+1242", flag: "🇧🇸", maxDigits: 7 },
  { code: "BH", name: "Bahrain", dial: "+973", flag: "🇧🇭", maxDigits: 8 },
  { code: "BD", name: "Bangladesh", dial: "+880", flag: "🇧🇩", maxDigits: 10 },
  { code: "BB", name: "Barbados", dial: "+1246", flag: "🇧🇧", maxDigits: 7 },
  { code: "BY", name: "Belarus", dial: "+375", flag: "🇧🇾", maxDigits: 10 },
  { code: "BE", name: "Belgium", dial: "+32", flag: "🇧🇪", maxDigits: 9 },
  { code: "BZ", name: "Belize", dial: "+501", flag: "🇧🇿", maxDigits: 7 },
  { code: "BJ", name: "Benin", dial: "+229", flag: "🇧🇯", maxDigits: 8 },
  { code: "BM", name: "Bermuda", dial: "+1441", flag: "🇧🇲", maxDigits: 7 },
  { code: "BT", name: "Bhutan", dial: "+975", flag: "🇧🇹", maxDigits: 8 },
  { code: "BO", name: "Bolivia", dial: "+591", flag: "🇧🇴", maxDigits: 8 },
  { code: "BA", name: "Bosnia & Herzegovina", dial: "+387", flag: "🇧🇦", maxDigits: 8 },
  { code: "BW", name: "Botswana", dial: "+267", flag: "🇧🇼", maxDigits: 8 },
  { code: "BR", name: "Brazil", dial: "+55", flag: "🇧🇷", maxDigits: 11 },
  { code: "BN", name: "Brunei", dial: "+673", flag: "🇧🇳", maxDigits: 7 },
  { code: "BG", name: "Bulgaria", dial: "+359", flag: "🇧🇬", maxDigits: 9 },
  { code: "BF", name: "Burkina Faso", dial: "+226", flag: "🇧🇫", maxDigits: 8 },
  { code: "BI", name: "Burundi", dial: "+257", flag: "🇧🇮", maxDigits: 8 },
  { code: "KH", name: "Cambodia", dial: "+855", flag: "🇰🇭", maxDigits: 9 },
  { code: "CM", name: "Cameroon", dial: "+237", flag: "🇨🇲", maxDigits: 9 },
  { code: "CA", name: "Canada", dial: "+1", flag: "🇨🇦", maxDigits: 10 },
  { code: "CV", name: "Cape Verde", dial: "+238", flag: "🇨🇻", maxDigits: 7 },
  { code: "KY", name: "Cayman Islands", dial: "+1345", flag: "🇰🇾", maxDigits: 7 },
  { code: "CF", name: "Central African Republic", dial: "+236", flag: "🇨🇫", maxDigits: 8 },
  { code: "TD", name: "Chad", dial: "+235", flag: "🇹🇩", maxDigits: 8 },
  { code: "CL", name: "Chile", dial: "+56", flag: "🇨🇱", maxDigits: 9 },
  { code: "CN", name: "China", dial: "+86", flag: "🇨🇳", maxDigits: 11 },
  { code: "CO", name: "Colombia", dial: "+57", flag: "🇨🇴", maxDigits: 10 },
  { code: "KM", name: "Comoros", dial: "+269", flag: "🇰🇲", maxDigits: 7 },
  { code: "CG", name: "Congo", dial: "+242", flag: "🇨🇬", maxDigits: 9 },
  { code: "CD", name: "Congo (DRC)", dial: "+243", flag: "🇨🇩", maxDigits: 9 },
  { code: "CK", name: "Cook Islands", dial: "+682", flag: "🇨🇰", maxDigits: 5 },
  { code: "CR", name: "Costa Rica", dial: "+506", flag: "🇨🇷", maxDigits: 8 },
  { code: "CI", name: "Côte d'Ivoire", dial: "+225", flag: "🇨🇮", maxDigits: 10 },
  { code: "HR", name: "Croatia", dial: "+385", flag: "🇭🇷", maxDigits: 9 },
  { code: "CU", name: "Cuba", dial: "+53", flag: "🇨🇺", maxDigits: 8 },
  { code: "CW", name: "Curaçao", dial: "+599", flag: "🇨🇼", maxDigits: 8 },
  { code: "CY", name: "Cyprus", dial: "+357", flag: "🇨🇾", maxDigits: 8 },
  { code: "CZ", name: "Czech Republic", dial: "+420", flag: "🇨🇿", maxDigits: 9 },
  { code: "DK", name: "Denmark", dial: "+45", flag: "🇩🇰", maxDigits: 8 },
  { code: "DJ", name: "Djibouti", dial: "+253", flag: "🇩🇯", maxDigits: 8 },
  { code: "DM", name: "Dominica", dial: "+1767", flag: "🇩🇲", maxDigits: 7 },
  { code: "DO", name: "Dominican Republic", dial: "+1809", flag: "🇩🇴", maxDigits: 10 },
  { code: "EC", name: "Ecuador", dial: "+593", flag: "🇪🇨", maxDigits: 9 },
  { code: "EG", name: "Egypt", dial: "+20", flag: "🇪🇬", maxDigits: 10 },
  { code: "SV", name: "El Salvador", dial: "+503", flag: "🇸🇻", maxDigits: 8 },
  { code: "GQ", name: "Equatorial Guinea", dial: "+240", flag: "🇬🇶", maxDigits: 9 },
  { code: "ER", name: "Eritrea", dial: "+291", flag: "🇪🇷", maxDigits: 7 },
  { code: "EE", name: "Estonia", dial: "+372", flag: "🇪🇪", maxDigits: 8 },
  { code: "SZ", name: "Eswatini", dial: "+268", flag: "🇸🇿", maxDigits: 8 },
  { code: "ET", name: "Ethiopia", dial: "+251", flag: "🇪🇹", maxDigits: 9 },
  { code: "FK", name: "Falkland Islands", dial: "+500", flag: "🇫🇰", maxDigits: 5 },
  { code: "FO", name: "Faroe Islands", dial: "+298", flag: "🇫🇴", maxDigits: 6 },
  { code: "FJ", name: "Fiji", dial: "+679", flag: "🇫🇯", maxDigits: 7 },
  { code: "FI", name: "Finland", dial: "+358", flag: "🇫🇮", maxDigits: 10 },
  { code: "FR", name: "France", dial: "+33", flag: "🇫🇷", maxDigits: 9 },
  { code: "GF", name: "French Guiana", dial: "+594", flag: "🇬🇫", maxDigits: 9 },
  { code: "PF", name: "French Polynesia", dial: "+689", flag: "🇵🇫", maxDigits: 8 },
  { code: "GA", name: "Gabon", dial: "+241", flag: "🇬🇦", maxDigits: 8 },
  { code: "GM", name: "Gambia", dial: "+220", flag: "🇬🇲", maxDigits: 7 },
  { code: "GE", name: "Georgia", dial: "+995", flag: "🇬🇪", maxDigits: 9 },
  { code: "DE", name: "Germany", dial: "+49", flag: "🇩🇪", maxDigits: 11 },
  { code: "GH", name: "Ghana", dial: "+233", flag: "🇬🇭", maxDigits: 9 },
  { code: "GI", name: "Gibraltar", dial: "+350", flag: "🇬🇮", maxDigits: 8 },
  { code: "GR", name: "Greece", dial: "+30", flag: "🇬🇷", maxDigits: 10 },
  { code: "GL", name: "Greenland", dial: "+299", flag: "🇬🇱", maxDigits: 6 },
  { code: "GD", name: "Grenada", dial: "+1473", flag: "🇬🇩", maxDigits: 7 },
  { code: "GP", name: "Guadeloupe", dial: "+590", flag: "🇬🇵", maxDigits: 9 },
  { code: "GU", name: "Guam", dial: "+1671", flag: "🇬🇺", maxDigits: 7 },
  { code: "GT", name: "Guatemala", dial: "+502", flag: "🇬🇹", maxDigits: 8 },
  { code: "GG", name: "Guernsey", dial: "+44", flag: "🇬🇬", maxDigits: 10 },
  { code: "GN", name: "Guinea", dial: "+224", flag: "🇬🇳", maxDigits: 9 },
  { code: "GW", name: "Guinea-Bissau", dial: "+245", flag: "🇬🇼", maxDigits: 7 },
  { code: "GY", name: "Guyana", dial: "+592", flag: "🇬🇾", maxDigits: 7 },
  { code: "HT", name: "Haiti", dial: "+509", flag: "🇭🇹", maxDigits: 8 },
  { code: "HN", name: "Honduras", dial: "+504", flag: "🇭🇳", maxDigits: 8 },
  { code: "HK", name: "Hong Kong", dial: "+852", flag: "🇭🇰", maxDigits: 8 },
  { code: "HU", name: "Hungary", dial: "+36", flag: "🇭🇺", maxDigits: 9 },
  { code: "IS", name: "Iceland", dial: "+354", flag: "🇮🇸", maxDigits: 7 },
  { code: "IN", name: "India", dial: "+91", flag: "🇮🇳", maxDigits: 10 },
  { code: "ID", name: "Indonesia", dial: "+62", flag: "🇮🇩", maxDigits: 12 },
  { code: "IR", name: "Iran", dial: "+98", flag: "🇮🇷", maxDigits: 10 },
  { code: "IQ", name: "Iraq", dial: "+964", flag: "🇮🇶", maxDigits: 10 },
  { code: "IE", name: "Ireland", dial: "+353", flag: "🇮🇪", maxDigits: 9 },
  { code: "IM", name: "Isle of Man", dial: "+44", flag: "🇮🇲", maxDigits: 10 },
  { code: "IL", name: "Israel", dial: "+972", flag: "🇮🇱", maxDigits: 9 },
  { code: "IT", name: "Italy", dial: "+39", flag: "🇮🇹", maxDigits: 10 },
  { code: "JM", name: "Jamaica", dial: "+1876", flag: "🇯🇲", maxDigits: 7 },
  { code: "JP", name: "Japan", dial: "+81", flag: "🇯🇵", maxDigits: 10 },
  { code: "JE", name: "Jersey", dial: "+44", flag: "🇯🇪", maxDigits: 10 },
  { code: "JO", name: "Jordan", dial: "+962", flag: "🇯🇴", maxDigits: 9 },
  { code: "KZ", name: "Kazakhstan", dial: "+7", flag: "🇰🇿", maxDigits: 10 },
  { code: "KE", name: "Kenya", dial: "+254", flag: "🇰🇪", maxDigits: 10 },
  { code: "KI", name: "Kiribati", dial: "+686", flag: "🇰🇮", maxDigits: 8 },
  { code: "KP", name: "North Korea", dial: "+850", flag: "🇰🇵", maxDigits: 10 },
  { code: "KR", name: "South Korea", dial: "+82", flag: "🇰🇷", maxDigits: 11 },
  { code: "XK", name: "Kosovo", dial: "+383", flag: "🇽🇰", maxDigits: 8 },
  { code: "KW", name: "Kuwait", dial: "+965", flag: "🇰🇼", maxDigits: 8 },
  { code: "KG", name: "Kyrgyzstan", dial: "+996", flag: "🇰🇬", maxDigits: 9 },
  { code: "LA", name: "Laos", dial: "+856", flag: "🇱🇦", maxDigits: 10 },
  { code: "LV", name: "Latvia", dial: "+371", flag: "🇱🇻", maxDigits: 8 },
  { code: "LB", name: "Lebanon", dial: "+961", flag: "🇱🇧", maxDigits: 8 },
  { code: "LS", name: "Lesotho", dial: "+266", flag: "🇱🇸", maxDigits: 8 },
  { code: "LR", name: "Liberia", dial: "+231", flag: "🇱🇷", maxDigits: 7 },
  { code: "LY", name: "Libya", dial: "+218", flag: "🇱🇾", maxDigits: 9 },
  { code: "LI", name: "Liechtenstein", dial: "+423", flag: "🇱🇮", maxDigits: 7 },
  { code: "LT", name: "Lithuania", dial: "+370", flag: "🇱🇹", maxDigits: 8 },
  { code: "LU", name: "Luxembourg", dial: "+352", flag: "🇱🇺", maxDigits: 9 },
  { code: "MO", name: "Macau", dial: "+853", flag: "🇲🇴", maxDigits: 8 },
  { code: "MK", name: "North Macedonia", dial: "+389", flag: "🇲🇰", maxDigits: 8 },
  { code: "MG", name: "Madagascar", dial: "+261", flag: "🇲🇬", maxDigits: 10 },
  { code: "MW", name: "Malawi", dial: "+265", flag: "🇲🇼", maxDigits: 9 },
  { code: "MY", name: "Malaysia", dial: "+60", flag: "🇲🇾", maxDigits: 10 },
  { code: "MV", name: "Maldives", dial: "+960", flag: "🇲🇻", maxDigits: 7 },
  { code: "ML", name: "Mali", dial: "+223", flag: "🇲🇱", maxDigits: 8 },
  { code: "MT", name: "Malta", dial: "+356", flag: "🇲🇹", maxDigits: 8 },
  { code: "MH", name: "Marshall Islands", dial: "+692", flag: "🇲🇭", maxDigits: 7 },
  { code: "MQ", name: "Martinique", dial: "+596", flag: "🇲🇶", maxDigits: 9 },
  { code: "MR", name: "Mauritania", dial: "+222", flag: "🇲🇷", maxDigits: 8 },
  { code: "MU", name: "Mauritius", dial: "+230", flag: "🇲🇺", maxDigits: 8 },
  { code: "YT", name: "Mayotte", dial: "+262", flag: "🇾🇹", maxDigits: 9 },
  { code: "MX", name: "Mexico", dial: "+52", flag: "🇲🇽", maxDigits: 10 },
  { code: "FM", name: "Micronesia", dial: "+691", flag: "🇫🇲", maxDigits: 7 },
  { code: "MD", name: "Moldova", dial: "+373", flag: "🇲🇩", maxDigits: 8 },
  { code: "MC", name: "Monaco", dial: "+377", flag: "🇲🇨", maxDigits: 9 },
  { code: "MN", name: "Mongolia", dial: "+976", flag: "🇲🇳", maxDigits: 8 },
  { code: "ME", name: "Montenegro", dial: "+382", flag: "🇲🇪", maxDigits: 8 },
  { code: "MS", name: "Montserrat", dial: "+1664", flag: "🇲🇸", maxDigits: 7 },
  { code: "MA", name: "Morocco", dial: "+212", flag: "🇲🇦", maxDigits: 9 },
  { code: "MZ", name: "Mozambique", dial: "+258", flag: "🇲🇿", maxDigits: 9 },
  { code: "MM", name: "Myanmar", dial: "+95", flag: "🇲🇲", maxDigits: 9 },
  { code: "NA", name: "Namibia", dial: "+264", flag: "🇳🇦", maxDigits: 9 },
  { code: "NR", name: "Nauru", dial: "+674", flag: "🇳🇷", maxDigits: 7 },
  { code: "NP", name: "Nepal", dial: "+977", flag: "🇳🇵", maxDigits: 10 },
  { code: "NL", name: "Netherlands", dial: "+31", flag: "🇳🇱", maxDigits: 9 },
  { code: "NC", name: "New Caledonia", dial: "+687", flag: "🇳🇨", maxDigits: 6 },
  { code: "NZ", name: "New Zealand", dial: "+64", flag: "🇳🇿", maxDigits: 9 },
  { code: "NI", name: "Nicaragua", dial: "+505", flag: "🇳🇮", maxDigits: 8 },
  { code: "NE", name: "Niger", dial: "+227", flag: "🇳🇪", maxDigits: 8 },
  { code: "NG", name: "Nigeria", dial: "+234", flag: "🇳🇬", maxDigits: 10 },
  { code: "NU", name: "Niue", dial: "+683", flag: "🇳🇺", maxDigits: 4 },
  { code: "NF", name: "Norfolk Island", dial: "+672", flag: "🇳🇫", maxDigits: 6 },
  { code: "MP", name: "Northern Mariana Islands", dial: "+1670", flag: "🇲🇵", maxDigits: 7 },
  { code: "NO", name: "Norway", dial: "+47", flag: "🇳🇴", maxDigits: 8 },
  { code: "OM", name: "Oman", dial: "+968", flag: "🇴🇲", maxDigits: 8 },
  { code: "PK", name: "Pakistan", dial: "+92", flag: "🇵🇰", maxDigits: 10 },
  { code: "PW", name: "Palau", dial: "+680", flag: "🇵🇼", maxDigits: 7 },
  { code: "PS", name: "Palestine", dial: "+970", flag: "🇵🇸", maxDigits: 9 },
  { code: "PA", name: "Panama", dial: "+507", flag: "🇵🇦", maxDigits: 8 },
  { code: "PG", name: "Papua New Guinea", dial: "+675", flag: "🇵🇬", maxDigits: 8 },
  { code: "PY", name: "Paraguay", dial: "+595", flag: "🇵🇾", maxDigits: 9 },
  { code: "PE", name: "Peru", dial: "+51", flag: "🇵🇪", maxDigits: 9 },
  { code: "PH", name: "Philippines", dial: "+63", flag: "🇵🇭", maxDigits: 10 },
  { code: "PL", name: "Poland", dial: "+48", flag: "🇵🇱", maxDigits: 9 },
  { code: "PT", name: "Portugal", dial: "+351", flag: "🇵🇹", maxDigits: 9 },
  { code: "PR", name: "Puerto Rico", dial: "+1787", flag: "🇵🇷", maxDigits: 10 },
  { code: "QA", name: "Qatar", dial: "+974", flag: "🇶🇦", maxDigits: 8 },
  { code: "RE", name: "Réunion", dial: "+262", flag: "🇷🇪", maxDigits: 9 },
  { code: "RO", name: "Romania", dial: "+40", flag: "🇷🇴", maxDigits: 9 },
  { code: "RU", name: "Russia", dial: "+7", flag: "🇷🇺", maxDigits: 10 },
  { code: "RW", name: "Rwanda", dial: "+250", flag: "🇷🇼", maxDigits: 9 },
  { code: "BL", name: "Saint Barthélemy", dial: "+590", flag: "🇧🇱", maxDigits: 9 },
  { code: "SH", name: "Saint Helena", dial: "+290", flag: "🇸🇭", maxDigits: 4 },
  { code: "KN", name: "Saint Kitts & Nevis", dial: "+1869", flag: "🇰🇳", maxDigits: 7 },
  { code: "LC", name: "Saint Lucia", dial: "+1758", flag: "🇱🇨", maxDigits: 7 },
  { code: "MF", name: "Saint Martin", dial: "+590", flag: "🇲🇫", maxDigits: 9 },
  { code: "PM", name: "Saint Pierre & Miquelon", dial: "+508", flag: "🇵🇲", maxDigits: 6 },
  { code: "VC", name: "Saint Vincent", dial: "+1784", flag: "🇻🇨", maxDigits: 7 },
  { code: "WS", name: "Samoa", dial: "+685", flag: "🇼🇸", maxDigits: 7 },
  { code: "SM", name: "San Marino", dial: "+378", flag: "🇸🇲", maxDigits: 10 },
  { code: "ST", name: "São Tomé & Príncipe", dial: "+239", flag: "🇸🇹", maxDigits: 7 },
  { code: "SA", name: "Saudi Arabia", dial: "+966", flag: "🇸🇦", maxDigits: 9 },
  { code: "SN", name: "Senegal", dial: "+221", flag: "🇸🇳", maxDigits: 9 },
  { code: "RS", name: "Serbia", dial: "+381", flag: "🇷🇸", maxDigits: 9 },
  { code: "SC", name: "Seychelles", dial: "+248", flag: "🇸🇨", maxDigits: 7 },
  { code: "SL", name: "Sierra Leone", dial: "+232", flag: "🇸🇱", maxDigits: 8 },
  { code: "SG", name: "Singapore", dial: "+65", flag: "🇸🇬", maxDigits: 8 },
  { code: "SX", name: "Sint Maarten", dial: "+1721", flag: "🇸🇽", maxDigits: 7 },
  { code: "SK", name: "Slovakia", dial: "+421", flag: "🇸🇰", maxDigits: 9 },
  { code: "SI", name: "Slovenia", dial: "+386", flag: "🇸🇮", maxDigits: 8 },
  { code: "SB", name: "Solomon Islands", dial: "+677", flag: "🇸🇧", maxDigits: 7 },
  { code: "SO", name: "Somalia", dial: "+252", flag: "🇸🇴", maxDigits: 8 },
  { code: "ZA", name: "South Africa", dial: "+27", flag: "🇿🇦", maxDigits: 9 },
  { code: "SS", name: "South Sudan", dial: "+211", flag: "🇸🇸", maxDigits: 9 },
  { code: "ES", name: "Spain", dial: "+34", flag: "🇪🇸", maxDigits: 9 },
  { code: "LK", name: "Sri Lanka", dial: "+94", flag: "🇱🇰", maxDigits: 9 },
  { code: "SD", name: "Sudan", dial: "+249", flag: "🇸🇩", maxDigits: 9 },
  { code: "SR", name: "Suriname", dial: "+597", flag: "🇸🇷", maxDigits: 7 },
  { code: "SE", name: "Sweden", dial: "+46", flag: "🇸🇪", maxDigits: 10 },
  { code: "CH", name: "Switzerland", dial: "+41", flag: "🇨🇭", maxDigits: 9 },
  { code: "SY", name: "Syria", dial: "+963", flag: "🇸🇾", maxDigits: 9 },
  { code: "TW", name: "Taiwan", dial: "+886", flag: "🇹🇼", maxDigits: 9 },
  { code: "TJ", name: "Tajikistan", dial: "+992", flag: "🇹🇯", maxDigits: 9 },
  { code: "TZ", name: "Tanzania", dial: "+255", flag: "🇹🇿", maxDigits: 9 },
  { code: "TH", name: "Thailand", dial: "+66", flag: "🇹🇭", maxDigits: 9 },
  { code: "TL", name: "Timor-Leste", dial: "+670", flag: "🇹🇱", maxDigits: 8 },
  { code: "TG", name: "Togo", dial: "+228", flag: "🇹🇬", maxDigits: 8 },
  { code: "TK", name: "Tokelau", dial: "+690", flag: "🇹🇰", maxDigits: 4 },
  { code: "TO", name: "Tonga", dial: "+676", flag: "🇹🇴", maxDigits: 7 },
  { code: "TT", name: "Trinidad & Tobago", dial: "+1868", flag: "🇹🇹", maxDigits: 7 },
  { code: "TN", name: "Tunisia", dial: "+216", flag: "🇹🇳", maxDigits: 8 },
  { code: "TR", name: "Turkey", dial: "+90", flag: "🇹🇷", maxDigits: 10 },
  { code: "TM", name: "Turkmenistan", dial: "+993", flag: "🇹🇲", maxDigits: 8 },
  { code: "TC", name: "Turks & Caicos", dial: "+1649", flag: "🇹🇨", maxDigits: 7 },
  { code: "TV", name: "Tuvalu", dial: "+688", flag: "🇹🇻", maxDigits: 6 },
  { code: "UG", name: "Uganda", dial: "+256", flag: "🇺🇬", maxDigits: 9 },
  { code: "UA", name: "Ukraine", dial: "+380", flag: "🇺🇦", maxDigits: 9 },
  { code: "AE", name: "United Arab Emirates", dial: "+971", flag: "🇦🇪", maxDigits: 9 },
  { code: "GB", name: "United Kingdom", dial: "+44", flag: "🇬🇧", maxDigits: 10 },
  { code: "US", name: "United States", dial: "+1", flag: "🇺🇸", maxDigits: 10 },
  { code: "UY", name: "Uruguay", dial: "+598", flag: "🇺🇾", maxDigits: 8 },
  { code: "UZ", name: "Uzbekistan", dial: "+998", flag: "🇺🇿", maxDigits: 9 },
  { code: "VU", name: "Vanuatu", dial: "+678", flag: "🇻🇺", maxDigits: 7 },
  { code: "VA", name: "Vatican City", dial: "+379", flag: "🇻🇦", maxDigits: 10 },
  { code: "VE", name: "Venezuela", dial: "+58", flag: "🇻🇪", maxDigits: 7 },
  { code: "VN", name: "Vietnam", dial: "+84", flag: "🇻🇳", maxDigits: 10 },
  { code: "VG", name: "British Virgin Islands", dial: "+1284", flag: "🇻🇬", maxDigits: 7 },
  { code: "VI", name: "U.S. Virgin Islands", dial: "+1340", flag: "🇻🇮", maxDigits: 7 },
  { code: "WF", name: "Wallis & Futuna", dial: "+681", flag: "🇼🇫", maxDigits: 6 },
  { code: "YE", name: "Yemen", dial: "+967", flag: "🇾🇪", maxDigits: 9 },
  { code: "ZM", name: "Zambia", dial: "+260", flag: "🇿🇲", maxDigits: 9 },
  { code: "ZW", name: "Zimbabwe", dial: "+263", flag: "🇿🇼", maxDigits: 9 },
];
